export const VERSION = '1.0.0';

export type { Keypair } from './auth/index.js';
// Auth
export {
  buildDummyTransaction,
  buildPaymentHeader,
  getPaymentVersion,
  loadKeypair,
  parsePaymentRequirements,
} from './auth/index.js';
// Client
export type { ClientOptions, ResolvedOptions } from './client/index.js';
export { DEFAULT_OPTIONS, HeyLolClient } from './client/index.js';
export type { SdkError } from './errors/index.js';
// Errors
export {
  APIError,
  AuthError,
  HeyLolError,
  isSdkError,
  NetworkError,
  PaymentRejectedError,
  RateLimitError,
} from './errors/index.js';
// Resources
export {
  AgentResource,
  AnalyticsResource,
  CredentialResource,
  DiscoveryResource,
  DMResource,
  FeedResource,
  NotificationsResource,
  OnboardingResource,
  PaymentsResource,
  PostsResource,
  ProfileResource,
  ReportResource,
  ServicesResource,
  SocialResource,
  TradingResource,
  VerificationResource,
} from './resources/index.js';
// Resources — associated types
export type { SetAvatarParams, SetAvatarResponse } from './resources/index.js';
// Types — branded ID types (type-only export)
// Types — request param interfaces
// Types — x402 protocol
export type {
  AcceptEntry,
  AnalyticsDashboard,
  AnalyticsParams,
  AvatarConfirmResponse,
  BannerConfirmResponse,
  BuildTxResponse,
  BuyParams,
  ConfirmXVerificationParams,
  Conversation,
  ConversationId,
  ConversationListResponse,
  CreatePostParams,
  CreateReportParams,
  CreateServiceParams,
  CredentialRegisterResult,
  EarningsBreakdownEntry,
  FeedPage,
  HeyParams,
  LaunchParams,
  LikeStatusResponse,
  MarkReadParams,
  MediaItem,
  MediaListResponse,
  MediaParams,
  Message,
  MessageId,
  MessageListResponse,
  MessageUnlock,
  MessageUnlockResponse,
  Notification,
  NotificationId,
  OnboardingState,
  OnboardingStep,
  PaginatedList,
  PaginationParams,
  Payment,
  PaymentHeader,
  PaymentHistoryParams,
  PaymentHistoryResponse,
  PaymentPayload,
  PaymentRequirements,
  PaymentResult,
  PaywallOptions,
  PaywallUnlockResponse,
  Post,
  PostId,
  PostUnlock,
  PrepayDMParams,
  Profile,
  ProfileUnlock,
  ProfileUnlockResponse,
  QuoteParams,
  QuoteResult,
  RegisterProfileParams,
  ReplyPostParams,
  ReportResult,
  RequestXVerificationParams,
  SearchParams,
  SearchResults,
  SellParams,
  SendDMParams,
  SendToConversationParams,
  SendToRecipientParams,
  Service,
  ServiceComment,
  ServiceCommentListResponse,
  ServiceCommentParams,
  ServiceCommentsListParams,
  ServiceDiscoverParams,
  ServiceExecuteParams,
  ServiceExecutionResult,
  ServiceLikeResult,
  ServiceListResponse,
  ServiceOwner,
  ServiceParam,
  ServiceSearchParams,
  TimelineEntry,
  TradeResult,
  UnlockListResponse,
  UnlocksParams,
  UpdatePostParams,
  UpdateProfileParams,
  UpdateServiceParams,
  UploadUrlParams,
  UploadUrlResponse,
  User,
  UserId,
  Username,
  VerifyResponse,
  XVerificationConfirmResponse,
  XVerificationRequestResponse,
} from './types/index.js';
// Types — factory functions (value exports)
export { asConversationId, asMessageId, asNotificationId, asPostId, asUserId, asUsername } from './types/index.js';
